### ISSUE TITLE
BurpExtenderUtilities is incompatible with the legacy extensions

### ISSUE THREAD

**Issue by irsdl** [CoreyD97/BurpExtenderUtilities#9]
The `Preferences` function has changed as is not backward compatible. Given we use `implementation "com.github.CoreyD97:BurpExtenderUtilities:-SNAPSHOT"` in gradle settings, it is going to break all the extensions using it unless they also update :'(

**Comment by irsdl** [comment]
Why is this an issue? My extension can support MontoyaAPI but when that's not available, I still need to use the old version of this library which is now incompatible. I think you should just make another one for Montoya API and revert this one back so we can use two different libraries based on the settings.

**Comment by CoreyD97** [comment]
That's a good point. I did consider creating a separate repo for the Montoya version, but didn't because you can still use old versions by using `implementation "com.github.CoreyD97:BurpExtenderUtilities:[Commit Hash]"`. Though, as you mentioned it would be much more sensible to have a separate library for this. 

I'll look into doing this soon.

**Comment by irsdl** [comment]
I didn't have the hash and I was using the `-SNAPSHOT` :( and because there is no README, I couldn't find its maven repo with the hashes in on time for my internal talk in the office 😢 Montoya Api has changed everything and now I need to rebuild the whole thing - there is no easy way to tell it to respect the old stuff especially around the UI.

With the Montoya API and its new way of storing stuff, do we still need this library to store stuff in the sitemap? What are your thoughts on this?

**Comment by CoreyD97** [comment]
Fixed. This repo has been rolled back and the Montoya changes moved to https://github.com/CoreyD97/Burp-Montoya-Utilities
